# Generated by Django 4.2.11 on 2026-04-26 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=20)),
                ('activity_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('meditation', 'Meditation'), ('music', 'Music Playlist'), ('physical', 'Physical Activity'), ('social', 'Social Activity'), ('journaling', 'Journaling'), ('mindfulness', 'Mindfulness'), ('gratitude', 'Gratitude Practice')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=10)),
                ('reason', models.TextField()),
                ('effectiveness_rating', models.FloatField(default=0.0)),
                ('user_tried', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('communication_style', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('supportive', 'Supportive'), ('motivational', 'Motivational')], default='supportive', max_length=20)),
                ('preferred_activities', models.JSONField(blank=True, default=list)),
                ('avoided_activities', models.JSONField(blank=True, default=list)),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('anonymous', 'Anonymous')], default='private', max_length=20)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('notification_time', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emosense_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.CharField(choices=[('stress_relief', 'Reduce Stress'), ('mood_boost', 'Boost Mood'), ('sleep', 'Better Sleep'), ('focus', 'Improve Focus'), ('general', 'General Wellness')], default='general', max_length=50)),
                ('use_ai_recommendations', models.BooleanField(default=True)),
                ('recommendation_frequency', models.CharField(choices=[('always', 'Always'), ('sometimes', 'Sometimes'), ('rarely', 'Rarely')], default='sometimes', max_length=20)),
                ('share_data_for_improvement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='emotion.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('angry', 'Angry'), ('disgusted', 'Disgusted'), ('fearful', 'Fearful'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('surprised', 'Surprised')], max_length=20)),
                ('confidence', models.FloatField()),
                ('time_of_day', models.CharField(blank=True, choices=[('morning', 'Morning (6-12)'), ('afternoon', 'Afternoon (12-18)'), ('evening', 'Evening (18-24)'), ('night', 'Night (0-6)')], max_length=20, null=True)),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True)),
                ('user_confirmed', models.BooleanField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('image_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('most_common_emotion', models.CharField(blank=True, max_length=20)),
                ('second_common_emotion', models.CharField(blank=True, max_length=20)),
                ('peak_stress_time', models.CharField(blank=True, max_length=20)),
                ('peak_happy_time', models.CharField(blank=True, max_length=20)),
                ('weekly_pattern', models.JSONField(default=dict)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('total_predictions', models.IntegerField(default=0)),
                ('accuracy_feedback_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_pattern', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
