'use client'

import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Language = 'en' | 'si'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.detect': 'Detect',
    'nav.wellness': 'Wellness',
    'nav.luma': 'Luma AI',
    'nav.history': 'History',
    'nav.resources': 'Resources',
    'nav.profile': 'Profile',
    'nav.home': 'Home',
    'nav.book': 'Book Counselor',
    'nav.settings': 'Settings',
    'nav.privacy': 'Privacy & Data',
    'nav.contact': 'Contact Us',
    'nav.faq': 'FAQ',
    'nav.about': 'About',
    'nav.login': 'Log in',
    'nav.signup': 'Sign up',
    'nav.logout': 'Logout',
    'nav.switch_sinhala': 'Switch to Sinhala',
    'nav.switch_english': 'Switch to English',
    'home.badge': 'AI-Powered Emotional Wellness',
    'home.title': 'Understand Your Emotions, Transform Your Wellbeing',
    'home.description': 'EmoSense uses AI to detect your emotions and connects you with personalized wellness tools, an AI therapist named Luma, and campus mental health resources — all in one place.',
    'home.analyze': 'Analyze My Emotion',
    'home.luma': 'Talk to Luma',
    'auth.forgot_password': 'Forgot password?',
    'auth.signing_in': 'Signing in...',
    'auth.creating_account': 'Creating account...',
    'auth.forgot_prompt': 'Reset your password',
    'auth.login_heading': 'Sign In to continue your wellness journey',
    'auth.register_heading': 'Create Your Account',
    'auth.register_subheading': 'Start your emotional wellness journey today',
    'auth.admin_prompt': 'Are you an admin?',
    'auth.admin_link': 'Sign in to admin panel',
    'auth.password_mismatch': 'Passwords do not match',
    'auth.password_short': 'Password must be at least 6 characters',
    'auth.registration_failed': 'Registration failed',
    'auth.login_failed': 'Login failed',
    'auth.welcome_back': 'Welcome back! Redirecting to dashboard...',
    'auth.account_created': 'Account created! Welcome to EmoSense.',
    'about.title': 'About EmoSense',
    'about.subtitle': 'Our mission, values, and what makes us different',
    'about.mission_title': 'Our Mission',
    'about.mission_body': 'EmoSense empowers university students to understand, track, and improve their emotional wellbeing through AI-powered emotion detection, personalized wellness tools, and accessible mental health resources — all within a safe, private, and supportive platform.',
    'about.values_title': 'Our Values',
    'about.features_title': 'Key Features',
    'about.disclaimer_title': 'Important Disclaimer',
    'about.disclaimer_body': 'EmoSense is an educational and wellness support tool, NOT a substitute for professional mental health services. The AI emotion detection and Luma AI therapist are designed to provide general wellness support and should not be relied upon for clinical diagnosis or treatment. If you are experiencing a mental health crisis, please contact emergency services or call the national helpline at 1926.',
    'about.cta': 'Get Started with EmoSense',
    'contact.title': 'Contact Us',
    'contact.subtitle': "Have a question or feedback? We'd love to hear from you.",
    'contact.message_title': 'Send us a Message',
    'contact.message_subtitle': 'Fill out the form below and we will get back to you within 24 hours.',
    'contact.sent_title': 'Message Sent!',
    'contact.sent_body': 'Thank you for reaching out. Our team will review your message and respond within 24 hours.',
    'contact.sent_button': 'Send Another Message',
    'contact.name': 'Full Name',
    'contact.name_placeholder': 'Your name',
    'contact.email': 'Email',
    'contact.email_placeholder': 'you@university.edu',
    'contact.subject': 'Subject',
    'contact.subject_placeholder': 'Select a subject',
    'contact.message': 'Message',
    'contact.message_placeholder': 'How can we help you?',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.email_label': 'Email',
    'contact.phone_label': 'Phone',
    'contact.address_label': 'Address',
    'contact.hours_label': 'Hours',
    'contact.general': 'General Inquiry',
    'contact.technical': 'Technical Support',
    'contact.feedback': 'Feedback',
    'contact.counseling': 'Counseling Services',
    'contact.privacy': 'Privacy Concerns',
    'contact.other': 'Other',
    'footer.description': 'AI-powered emotion wellness platform designed for university students. Understand your emotions, get personalized support, and thrive.',
    'footer.disclaimer': 'EmoSense is not a replacement for professional mental health services. If you are in crisis, please contact emergency services.',
    'footer.made_with': 'Made with',
    'footer.for': 'for student wellbeing',
    'footer.features': 'Features',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms of Use',
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome to your Wellness Hub',
    'dashboard.emotion': 'Check Your Emotion',
    'dashboard.chat': 'Chat with Luma',
    'dashboard.affirmation': 'Daily Affirmation',
    'dashboard.wellness': 'Wellness Activities',
    'dashboard.history': 'Emotion History',
    'dashboard.resources': 'Resources',
    'dashboard.settings': 'Settings',
    'dashboard.profile': 'Profile',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.logout': 'Log Out',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.fullname': 'Full Name',
    'auth.already_member': 'Already have an account?',
    'auth.no_account': "Don't have an account?",
    'auth.login': 'Sign In to continue your wellness journey',
    'auth.register': 'Create Your Account',    'auth.forgot': 'Forgot password?',
    'auth.confirm_password': 'Confirm Password',    'emotion.title': 'Emotion Detection',
    'emotion.capture': 'Capture & Analyze',
    'emotion.upload': 'Upload Image',
    'emotion.analyze': 'Analyze Emotion',
    'emotion.reset': 'Reset',
    'emotion.result': 'Analysis Result',
    'luma.title': 'Luma - AI Wellness Companion',
    'luma.placeholder': "Tell Luma how you're feeling...",
    'luma.stressed': 'I feel stressed',
    'luma.relax': 'Help me relax',
    'luma.motivation': 'I need motivation',
    'luma.breathing': 'Breathing exercise',
    'luma.new_chat': 'New Chat',
    'luma.resources': 'Resources',
    'wellness.title': 'Wellness Hub',
    'wellness.activities': 'Activities and tools for your emotional wellbeing',
    'wellness.affirmation': 'Daily Affirmation',
    'wellness.breathing': 'Breathing Exercises',
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Privacy',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
  },
  si: {
    'nav.dashboard': 'උපකරණ පුවරුව',
    'nav.detect': 'හඳුනාගන්න',
    'nav.wellness': 'සුවතාවය',
    'nav.luma': 'Luma AI',
    'nav.history': 'ඉතිහාසය',
    'nav.resources': 'සම්පත්',
    'nav.profile': 'පැතිකඩ',
    'nav.home': 'මුල් පිටුව',
    'nav.book': 'උපදේශකයෙකු වෙන්කරන්න',
    'nav.settings': 'සැකසුම්',
    'nav.privacy': 'පුද්ගලිකත්වය සහ දත්ත',
    'nav.contact': 'අප අමතන්න',
    'nav.faq': 'නිතර අසන ප්‍රශ්න',
    'nav.about': 'ගැන',
    'nav.login': 'ඇතුල් වන්න',
    'nav.signup': 'ලියාපදිංචි වන්න',
    'nav.logout': 'ඉවත් වන්න',
    'nav.switch_sinhala': 'සිංහලට මාරු වෙන්න',
    'nav.switch_english': 'ඉංග්‍රීසියට මාරු වෙන්න',
    'home.badge': 'AI මඟින් සක්‍රිය වූ චිත්තවේගීය සුවතාවය',
    'home.title': 'ඔබගේ හැඟීම් තේරුම් ගන්න, ඔබගේ යහපැවැත්ම වෙනස් කරන්න',
    'home.description': 'EmoSense ඔබගේ හැඟීම් හඳුනා ගැනීමට AI භාවිතා කරයි සහ ඔබව පුද්ගලික සුවතා මෙවලම්, Luma නම් AI therapist කෙනෙකු, සහ කැම්පස් මානසික සෞඛ්‍ය සම්පත් සමඟ එක් කරයි — සියල්ල එක් ස්ථානයක.',
    'home.analyze': 'මගේ හැඟීම විශ්ලේෂණය කරන්න',
    'home.luma': 'Luma සමඟ කතා කරන්න',
    'auth.forgot_password': 'මුරපදය අමතකද?',
    'auth.signing_in': 'ඇතුල් වෙමින්...',
    'auth.creating_account': 'ගිණුම සාදමින්...',
    'auth.forgot_prompt': 'ඔබගේ මුරපදය නැවත සකසන්න',
    'auth.login_heading': 'ඔබගේ සුවතා ගමන ඉදිරියට යැවීමට ඇතුල් වන්න',
    'auth.register_heading': 'ඔබගේ ගිණුම සාදන්න',
    'auth.register_subheading': 'අදම ඔබගේ චිත්තවේගීය සුවතා ගමන ආරම්භ කරන්න',
    'auth.admin_prompt': 'ඔබ admin කෙනෙක්ද?',
    'auth.admin_link': 'Admin පැනලයට ඇතුල් වන්න',
    'auth.password_mismatch': 'මුරපද ගැළපෙන්නේ නැහැ',
    'auth.password_short': 'මුරපදය අවම වශයෙන් අක්ෂර 6ක් විය යුතුයි',
    'auth.registration_failed': 'ලියාපදිංචිය අසාර්ථක විය',
    'auth.login_failed': 'ඇතුල්වීම අසාර්ථක විය',
    'auth.welcome_back': 'නැවතත් සාදරයෙන් පිළිගනිමු! උපකරණ පුවරුවට යොමු කෙරේ...',
    'auth.account_created': 'ගිණුම සාර්ථකව සාදන ලදී! EmoSense වෙත සාදරයෙන් පිළිගනිමු.',
    'about.title': 'EmoSense ගැන',
    'about.subtitle': 'අපගේ මෙහෙවර, වටිනාකම්, සහ අපව වෙනස් කරන දේ',
    'about.mission_title': 'අපගේ මෙහෙවර',
    'about.mission_body': 'EmoSense විශ්වවිද්‍යාල සිසුන්ට AI-මඟින් සක්‍රිය වූ හැඟීම් හඳුනාගැනීම, පුද්ගලික සුවතා මෙවලම්, සහ ප්‍රවේශ විය හැකි මානසික සෞඛ්‍ය සම්පත් හරහා ඔවුන්ගේ චිත්තවේගීය යහපැවැත්ම තේරුම් ගැනීමට, නිරීක්ෂණය කිරීමට, සහ වැඩිදියුණු කිරීමට ශක්තිය ලබාදේ — ආරක්ෂිත, පෞද්ගලික, සහ සහාය දෙන වේදිකාවක් තුළ.',
    'about.values_title': 'අපගේ වටිනාකම්',
    'about.features_title': 'ප්‍රධාන විශේෂාංග',
    'about.disclaimer_title': 'වැදගත් වියාචනය',
    'about.disclaimer_body': 'EmoSense යනු අධ්‍යාපනික සහ සුවතා සහාය මෙවලමක් වන අතර වෘත්තීය මානසික සෞඛ්‍ය සේවාවන්ට ආදේශකයක් නොවේ. AI හැඟීම් හඳුනාගැනීම සහ Luma AI therapist සාමාන්‍ය සුවතා සහාය ලබා දීමට නිර්මාණය කර ඇති අතර සායනික රෝග විනිශ්චය හෝ ප්‍රතිකාර සඳහා යොදා නොගත යුතුය. ඔබට මානසික අර්බුදයක් තිබේ නම්, කරුණාකර හදිසි සේවා අමතන්න හෝ 1926 ජාතික helpline අමතන්න.',
    'about.cta': 'EmoSense සමඟ ආරම්භ කරන්න',
    'contact.title': 'අප අමතන්න',
    'contact.subtitle': 'ප්‍රශ්නයක් හෝ ප්‍රතිචාරයක් තිබේද? අපට අසන්න කැමතියි.',
    'contact.message_title': 'අපට පණිවිඩයක් යවන්න',
    'contact.message_subtitle': 'පහත පෝරමය පුරවා යවන්න, පැය 24ක් ඇතුළත අපි පිළිතුරු දෙන්නෙමු.',
    'contact.sent_title': 'පණිවිඩය යවන ලදී!',
    'contact.sent_body': 'සම්බන්ධ වීම සඳහා ස්තූතියි. අපගේ කණ්ඩායම ඔබගේ පණිවිඩය සමාලෝචනය කර පැය 24ක් ඇතුළත පිළිතුරු දෙනු ඇත.',
    'contact.sent_button': 'තවත් පණිවිඩයක් යවන්න',
    'contact.name': 'සම්පූර්ණ නම',
    'contact.name_placeholder': 'ඔබගේ නම',
    'contact.email': 'ඉ-තැපෑල',
    'contact.email_placeholder': 'you@university.edu',
    'contact.subject': 'මාතෘකාව',
    'contact.subject_placeholder': 'මාතෘකාවක් තෝරන්න',
    'contact.message': 'පණිවිඩය',
    'contact.message_placeholder': 'අපි ඔබට උදව් කරන්නේ කොහොමද?',
    'contact.send': 'පණිවිඩය යවන්න',
    'contact.sending': 'යවමින්...',
    'contact.email_label': 'ඉ-තැපෑල',
    'contact.phone_label': 'දුරකථනය',
    'contact.address_label': 'ලිපිනය',
    'contact.hours_label': 'වේලාවන්',
    'contact.general': 'සාමාන්‍ය විමසීම',
    'contact.technical': 'තාක්ෂණික සහාය',
    'contact.feedback': 'ප්‍රතිචාර',
    'contact.counseling': 'උපදේශන සේවා',
    'contact.privacy': 'පුද්ගලිකත්වය පිළිබඳ කරුණු',
    'contact.other': 'වෙනත්',
    'footer.description': 'විශ්වවිද්‍යාල සිසුන් සඳහා නිර්මාණය කළ AI-මඟින් සක්‍රිය වූ චිත්තවේගීය සුවතා වේදිකාවක්. ඔබගේ හැඟීම් තේරුම් ගන්න, පුද්ගලික සහාය ලබාගන්න, සහ සාර්ථක වන්න.',
    'footer.disclaimer': 'EmoSense වෘත්තීය මානසික සෞඛ්‍ය සේවාවන්ට ආදේශකයක් නොවේ. ඔබට අර්බුදයක් තිබේ නම්, කරුණාකර හදිසි සේවා අමතන්න.',
    'footer.made_with': 'සැදූයේ',
    'footer.for': 'සිසුන්ගේ සුවතාවය සඳහා',
    'footer.features': 'විශේෂාංග',
    'footer.support': 'සහාය',
    'footer.legal': 'නීතිමය',
    'footer.terms': 'භාවිත නියමයන්',
    'dashboard.title': ' Dashboard එක',
    'dashboard.welcome': 'ඔබගේ Wellness Hub එකට සාදරයි',
    'dashboard.emotion': 'ඔබගේ හැඟීම පරීක්ෂා කරන්න',
    'dashboard.chat': 'Luma සමඟ කතා කරන්න',
    'dashboard.affirmation': 'දෛනික නිකුතුවල පෙනුම',
    'dashboard.wellness': 'Wellness කටයුතු',
    'dashboard.history': 'හැඟීම් ඉතිහාසය',
    'dashboard.resources': 'සම්පත්',
    'dashboard.settings': 'සැකසුම්',
    'dashboard.profile': 'පැතිකඩ',
    'auth.signin': 'ඇතුල් වන්න',
    'auth.signup': 'ලියාපදිංචි වන්න',
    'auth.logout': 'ඉවත් වන්න',
    'auth.username': 'භාවිතා නම',
    'auth.password': 'මුරපදය',
    'auth.email': 'ඉ-තැපෑල',
    'auth.fullname': 'සම්පූර්ණ නම',
    'auth.already_member': 'ඔබට දැනටමත් ගිණුමක් තිබේ ද?',
    'auth.no_account': 'ඔබට ගිණුමක් නොමැතිද?',
    'auth.login': 'ඔබගේ wellness ගමනෙන් ඉදිරියට යාමට ඇතුල් වන්න',
    'auth.register': 'ඔබගේ ගිණුම සාදන්න',
    'auth.forgot': 'මුරපදය අමතකයි ද?',
    'auth.confirm_password': 'මුරපදය තහවුරු කරන්න',
    'emotion.title': 'හැඟීම සනාក්ෂණය',
    'emotion.capture': 'ග්‍රහණ කරන්න & විශ්ලේෂණ කරන්න',
    'emotion.upload': 'පින්තූරය උඩුගත කරන්න',
    'emotion.analyze': 'හැඟීම විශ්ලේෂණ කරන්න',
    'emotion.reset': 'ප්‍රතිසිටුවන්න',
    'emotion.result': 'විශ්ලේෂණ ප්‍රතිඵලය',
    'luma.title': 'Luma - AI Wellness සহකරු',
    'luma.placeholder': 'Luma ට ඔබ කෙතරම් හැඟෙන්නේ ඒ කියන්න...',
    'luma.stressed': 'මම පීඩිතයි',
    'luma.relax': 'මට විශ්‍රාම ගැනීමට උදව් කරන්න',
    'luma.motivation': 'මට ප්‍රේරණය අවශ්‍යය',
    'luma.breathing': 'හුස්ම ව්‍යායාම',    'luma.new_chat': 'නව කතාව',
    'luma.resources': 'සම්පත්',    'wellness.title': 'Wellness Hub එක',
    'wellness.activities': 'ඔබගේ චිත්තවේගී යතුරුවර සඳහා කටයුතු සහ මෙවලම්',
    'wellness.affirmation': 'දෛනික නිකුතුවල පෙනුම',
    'wellness.breathing': 'හුස්ම ව්‍යායාම',
    'settings.title': 'සැකසුම්',
    'settings.appearance': 'පෙනුම',
    'settings.notifications': 'දැනුම්කිරීම්',
    'settings.privacy': 'පෞද්ගලිකත්වය',
    'settings.language': 'භාෂාව',
    'settings.theme': 'තේමාව',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem('language') as Language | null
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'si')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key
  }

  if (!mounted) {
    return <>{children}</>
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    // Return a default fallback during SSR/hydration
    return {
      language: 'en' as Language,
      setLanguage: () => {},
      t: (key: string) => key
    }
  }
  return context
}
